name: Publish Package to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false # use caching via later commands

      # - name: Get pnpm store directory
      #   shell: bash
      #   run: |
      #     echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # - uses: actions/cache@v3
      #   name: Setup pnpm cache
      #   with:
      #     path: ${{ env.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      # - name: Install dependencies
      #   run: pnpm install --no-frozen-lockfile

      # - name: Build
      #   run: pnpm build

      - uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: ${{ steps.publish.outputs.type }}
        run: echo "$PCKG_ID published to $PCKG_TAG, old version was [$OLD_VER]"
        env:
          OLD_VER: ${{ steps.publish.outputs.old-version }}
          PCKG_ID: ${{ steps.publish.outputs.id }}
          PCKG_TAG: ${{ steps.publish.outputs.tag }}
